# This workflow will build a .NET project

name: STIC_BULD_CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: ["master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup MsBuild
      uses: actions/setup-dotnet@v1
      
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.1.1
    
    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1
        
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE
      
    - name: Restore NuGet packages
      run: dotnet restore
      
    - name: Build the solution
      run: msbuild.exe StlToInpConverter.sln /p:configuration="Release"
